// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateAuthTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidAuthTokenByHash = `-- name: GetValidAuthTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM auth_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetValidAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getValidAuthTokenByHash, tokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const useAuthToken = `-- name: UseAuthToken :one
UPDATE auth_tokens
SET used_at = NOW()
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

func (q *Queries) UseAuthToken(ctx context.Context, tokenHash string) (AuthToken, error) {
	row := q.db.QueryRow(ctx, useAuthToken, tokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
