// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, slug, default_language, created_at, updated_at, stripe_customer_id, stripe_subscription_id, subscription_status, trial_ends_at, billing_email FROM companies WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.BillingEmail,
	)
	return i, err
}

const updateCompanyTier = `-- name: UpdateCompanyTier :one
UPDATE companies
SET subscription_status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, default_language, created_at, updated_at, stripe_customer_id, stripe_subscription_id, subscription_status, trial_ends_at, billing_email
`

type UpdateCompanyTierParams struct {
	ID                 pgtype.UUID `json:"id"`
	SubscriptionStatus string      `json:"subscription_status"`
}

func (q *Queries) UpdateCompanyTier(ctx context.Context, arg UpdateCompanyTierParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompanyTier, arg.ID, arg.SubscriptionStatus)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.BillingEmail,
	)
	return i, err
}
