// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations
SET accepted_at = NOW()
WHERE token = $1
  AND accepted_at IS NULL
  AND expires_at > NOW()
RETURNING id, company_id, email, role, token, accepted_at, expires_at, created_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (company_id, email, role, token, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, email, role, token, accepted_at, expires_at, created_at
`

type CreateInvitationParams struct {
	CompanyID pgtype.UUID        `json:"company_id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.CompanyID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, company_id, email, role, token, accepted_at, expires_at, created_at FROM invitations WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInvitationByEmailAndCompany = `-- name: GetPendingInvitationByEmailAndCompany :one
SELECT id, company_id, email, role, token, accepted_at, expires_at, created_at FROM invitations
WHERE company_id = $1
  AND email = $2
  AND accepted_at IS NULL
  AND expires_at > NOW()
`

type GetPendingInvitationByEmailAndCompanyParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Email     string      `json:"email"`
}

func (q *Queries) GetPendingInvitationByEmailAndCompany(ctx context.Context, arg GetPendingInvitationByEmailAndCompanyParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByEmailAndCompany, arg.CompanyID, arg.Email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidInvitationByToken = `-- name: GetValidInvitationByToken :one
SELECT id, company_id, email, role, token, accepted_at, expires_at, created_at FROM invitations
WHERE token = $1
  AND accepted_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetValidInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getValidInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
