// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobTag = `-- name: CreateJobTag :one
INSERT INTO job_tags (job_id, tag)
VALUES ($1, $2)
RETURNING id, job_id, tag
`

type CreateJobTagParams struct {
	JobID pgtype.UUID `json:"job_id"`
	Tag   string      `json:"tag"`
}

func (q *Queries) CreateJobTag(ctx context.Context, arg CreateJobTagParams) (JobTag, error) {
	row := q.db.QueryRow(ctx, createJobTag, arg.JobID, arg.Tag)
	var i JobTag
	err := row.Scan(&i.ID, &i.JobID, &i.Tag)
	return i, err
}

const deleteJobTag = `-- name: DeleteJobTag :exec
DELETE FROM job_tags WHERE job_id = $1 AND tag = $2
`

type DeleteJobTagParams struct {
	JobID pgtype.UUID `json:"job_id"`
	Tag   string      `json:"tag"`
}

func (q *Queries) DeleteJobTag(ctx context.Context, arg DeleteJobTagParams) error {
	_, err := q.db.Exec(ctx, deleteJobTag, arg.JobID, arg.Tag)
	return err
}

const listJobTagsByJob = `-- name: ListJobTagsByJob :many
SELECT id, job_id, tag FROM job_tags WHERE job_id = $1
`

func (q *Queries) ListJobTagsByJob(ctx context.Context, jobID pgtype.UUID) ([]JobTag, error) {
	rows, err := q.db.Query(ctx, listJobTagsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobTag{}
	for rows.Next() {
		var i JobTag
		if err := rows.Scan(&i.ID, &i.JobID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
