// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_recommendations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobRecommendation = `-- name: CreateJobRecommendation :one
INSERT INTO job_recommendations (job_id, description, urgency, estimated_cost_range)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, description, urgency, estimated_cost_range, resolved, resolved_job_id
`

type CreateJobRecommendationParams struct {
	JobID              pgtype.UUID `json:"job_id"`
	Description        string      `json:"description"`
	Urgency            string      `json:"urgency"`
	EstimatedCostRange pgtype.Text `json:"estimated_cost_range"`
}

func (q *Queries) CreateJobRecommendation(ctx context.Context, arg CreateJobRecommendationParams) (JobRecommendation, error) {
	row := q.db.QueryRow(ctx, createJobRecommendation,
		arg.JobID,
		arg.Description,
		arg.Urgency,
		arg.EstimatedCostRange,
	)
	var i JobRecommendation
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Description,
		&i.Urgency,
		&i.EstimatedCostRange,
		&i.Resolved,
		&i.ResolvedJobID,
	)
	return i, err
}

const listJobRecommendationsByJob = `-- name: ListJobRecommendationsByJob :many
SELECT id, job_id, description, urgency, estimated_cost_range, resolved, resolved_job_id FROM job_recommendations WHERE job_id = $1
`

func (q *Queries) ListJobRecommendationsByJob(ctx context.Context, jobID pgtype.UUID) ([]JobRecommendation, error) {
	rows, err := q.db.Query(ctx, listJobRecommendationsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobRecommendation{}
	for rows.Next() {
		var i JobRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Description,
			&i.Urgency,
			&i.EstimatedCostRange,
			&i.Resolved,
			&i.ResolvedJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveJobRecommendation = `-- name: ResolveJobRecommendation :one
UPDATE job_recommendations
SET resolved = true,
    resolved_job_id = $2
WHERE id = $1
RETURNING id, job_id, description, urgency, estimated_cost_range, resolved, resolved_job_id
`

type ResolveJobRecommendationParams struct {
	ID            pgtype.UUID `json:"id"`
	ResolvedJobID pgtype.UUID `json:"resolved_job_id"`
}

func (q *Queries) ResolveJobRecommendation(ctx context.Context, arg ResolveJobRecommendationParams) (JobRecommendation, error) {
	row := q.db.QueryRow(ctx, resolveJobRecommendation, arg.ID, arg.ResolvedJobID)
	var i JobRecommendation
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Description,
		&i.Urgency,
		&i.EstimatedCostRange,
		&i.Resolved,
		&i.ResolvedJobID,
	)
	return i, err
}
