// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_materials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobMaterial = `-- name: CreateJobMaterial :one
INSERT INTO job_materials (job_id, name, quantity, unit)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, name, quantity, unit
`

type CreateJobMaterialParams struct {
	JobID    pgtype.UUID `json:"job_id"`
	Name     string      `json:"name"`
	Quantity pgtype.Text `json:"quantity"`
	Unit     pgtype.Text `json:"unit"`
}

func (q *Queries) CreateJobMaterial(ctx context.Context, arg CreateJobMaterialParams) (JobMaterial, error) {
	row := q.db.QueryRow(ctx, createJobMaterial,
		arg.JobID,
		arg.Name,
		arg.Quantity,
		arg.Unit,
	)
	var i JobMaterial
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}

const deleteJobMaterial = `-- name: DeleteJobMaterial :exec
DELETE FROM job_materials WHERE id = $1
`

func (q *Queries) DeleteJobMaterial(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJobMaterial, id)
	return err
}

const listJobMaterialsByJob = `-- name: ListJobMaterialsByJob :many
SELECT id, job_id, name, quantity, unit FROM job_materials WHERE job_id = $1
`

func (q *Queries) ListJobMaterialsByJob(ctx context.Context, jobID pgtype.UUID) ([]JobMaterial, error) {
	rows, err := q.db.Query(ctx, listJobMaterialsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobMaterial{}
	for rows.Next() {
		var i JobMaterial
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Quantity,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
