// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    company_id, technician_id, client_name, client_email, client_phone,
    job_address, job_lat, job_lng, job_type, technician_notes, audio_url, photo_urls,
    detected_language, report_language
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, company_id, technician_id, client_name, client_email, client_phone, job_address, job_lat, job_lng, job_type, technician_notes, submitted_at, completed_at, pipeline_status, audio_url, photo_urls, pdf_url, email_sent_at, created_at, updated_at, transcript, ai_summary, ai_work_performed, ai_follow_up_notes, ai_warranty_notes, ai_job_category, ai_client_sentiment, ai_labor_hours, ai_follow_up_required, ai_safety_concerns, ai_tags, ai_raw_json, ai_model_used, ai_processed_at, detected_language, report_language
`

type CreateJobParams struct {
	CompanyID        pgtype.UUID    `json:"company_id"`
	TechnicianID     pgtype.UUID    `json:"technician_id"`
	ClientName       string         `json:"client_name"`
	ClientEmail      pgtype.Text    `json:"client_email"`
	ClientPhone      pgtype.Text    `json:"client_phone"`
	JobAddress       pgtype.Text    `json:"job_address"`
	JobLat           pgtype.Numeric `json:"job_lat"`
	JobLng           pgtype.Numeric `json:"job_lng"`
	JobType          pgtype.Text    `json:"job_type"`
	TechnicianNotes  pgtype.Text    `json:"technician_notes"`
	AudioUrl         pgtype.Text    `json:"audio_url"`
	PhotoUrls        []string       `json:"photo_urls"`
	DetectedLanguage pgtype.Text    `json:"detected_language"`
	ReportLanguage   pgtype.Text    `json:"report_language"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.CompanyID,
		arg.TechnicianID,
		arg.ClientName,
		arg.ClientEmail,
		arg.ClientPhone,
		arg.JobAddress,
		arg.JobLat,
		arg.JobLng,
		arg.JobType,
		arg.TechnicianNotes,
		arg.AudioUrl,
		arg.PhotoUrls,
		arg.DetectedLanguage,
		arg.ReportLanguage,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TechnicianID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.JobAddress,
		&i.JobLat,
		&i.JobLng,
		&i.JobType,
		&i.TechnicianNotes,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.PipelineStatus,
		&i.AudioUrl,
		&i.PhotoUrls,
		&i.PdfUrl,
		&i.EmailSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transcript,
		&i.AiSummary,
		&i.AiWorkPerformed,
		&i.AiFollowUpNotes,
		&i.AiWarrantyNotes,
		&i.AiJobCategory,
		&i.AiClientSentiment,
		&i.AiLaborHours,
		&i.AiFollowUpRequired,
		&i.AiSafetyConcerns,
		&i.AiTags,
		&i.AiRawJson,
		&i.AiModelUsed,
		&i.AiProcessedAt,
		&i.DetectedLanguage,
		&i.ReportLanguage,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, company_id, technician_id, client_name, client_email, client_phone, job_address, job_lat, job_lng, job_type, technician_notes, submitted_at, completed_at, pipeline_status, audio_url, photo_urls, pdf_url, email_sent_at, created_at, updated_at, transcript, ai_summary, ai_work_performed, ai_follow_up_notes, ai_warranty_notes, ai_job_category, ai_client_sentiment, ai_labor_hours, ai_follow_up_required, ai_safety_concerns, ai_tags, ai_raw_json, ai_model_used, ai_processed_at, detected_language, report_language FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TechnicianID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.JobAddress,
		&i.JobLat,
		&i.JobLng,
		&i.JobType,
		&i.TechnicianNotes,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.PipelineStatus,
		&i.AudioUrl,
		&i.PhotoUrls,
		&i.PdfUrl,
		&i.EmailSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transcript,
		&i.AiSummary,
		&i.AiWorkPerformed,
		&i.AiFollowUpNotes,
		&i.AiWarrantyNotes,
		&i.AiJobCategory,
		&i.AiClientSentiment,
		&i.AiLaborHours,
		&i.AiFollowUpRequired,
		&i.AiSafetyConcerns,
		&i.AiTags,
		&i.AiRawJson,
		&i.AiModelUsed,
		&i.AiProcessedAt,
		&i.DetectedLanguage,
		&i.ReportLanguage,
	)
	return i, err
}

const listJobsByCompany = `-- name: ListJobsByCompany :many
SELECT id, company_id, technician_id, client_name, client_email, client_phone, job_address, job_lat, job_lng, job_type, technician_notes, submitted_at, completed_at, pipeline_status, audio_url, photo_urls, pdf_url, email_sent_at, created_at, updated_at, transcript, ai_summary, ai_work_performed, ai_follow_up_notes, ai_warranty_notes, ai_job_category, ai_client_sentiment, ai_labor_hours, ai_follow_up_required, ai_safety_concerns, ai_tags, ai_raw_json, ai_model_used, ai_processed_at, detected_language, report_language FROM jobs WHERE company_id = $1 ORDER BY submitted_at DESC
`

func (q *Queries) ListJobsByCompany(ctx context.Context, companyID pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TechnicianID,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.JobAddress,
			&i.JobLat,
			&i.JobLng,
			&i.JobType,
			&i.TechnicianNotes,
			&i.SubmittedAt,
			&i.CompletedAt,
			&i.PipelineStatus,
			&i.AudioUrl,
			&i.PhotoUrls,
			&i.PdfUrl,
			&i.EmailSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Transcript,
			&i.AiSummary,
			&i.AiWorkPerformed,
			&i.AiFollowUpNotes,
			&i.AiWarrantyNotes,
			&i.AiJobCategory,
			&i.AiClientSentiment,
			&i.AiLaborHours,
			&i.AiFollowUpRequired,
			&i.AiSafetyConcerns,
			&i.AiTags,
			&i.AiRawJson,
			&i.AiModelUsed,
			&i.AiProcessedAt,
			&i.DetectedLanguage,
			&i.ReportLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByTechnician = `-- name: ListJobsByTechnician :many
SELECT id, company_id, technician_id, client_name, client_email, client_phone, job_address, job_lat, job_lng, job_type, technician_notes, submitted_at, completed_at, pipeline_status, audio_url, photo_urls, pdf_url, email_sent_at, created_at, updated_at, transcript, ai_summary, ai_work_performed, ai_follow_up_notes, ai_warranty_notes, ai_job_category, ai_client_sentiment, ai_labor_hours, ai_follow_up_required, ai_safety_concerns, ai_tags, ai_raw_json, ai_model_used, ai_processed_at, detected_language, report_language FROM jobs WHERE technician_id = $1 ORDER BY submitted_at DESC
`

func (q *Queries) ListJobsByTechnician(ctx context.Context, technicianID pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByTechnician, technicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TechnicianID,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.JobAddress,
			&i.JobLat,
			&i.JobLng,
			&i.JobType,
			&i.TechnicianNotes,
			&i.SubmittedAt,
			&i.CompletedAt,
			&i.PipelineStatus,
			&i.AudioUrl,
			&i.PhotoUrls,
			&i.PdfUrl,
			&i.EmailSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Transcript,
			&i.AiSummary,
			&i.AiWorkPerformed,
			&i.AiFollowUpNotes,
			&i.AiWarrantyNotes,
			&i.AiJobCategory,
			&i.AiClientSentiment,
			&i.AiLaborHours,
			&i.AiFollowUpRequired,
			&i.AiSafetyConcerns,
			&i.AiTags,
			&i.AiRawJson,
			&i.AiModelUsed,
			&i.AiProcessedAt,
			&i.DetectedLanguage,
			&i.ReportLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobPipeline = `-- name: UpdateJobPipeline :one
UPDATE jobs
SET pipeline_status = $2,
    transcript = $3,
    ai_summary = $4,
    ai_work_performed = $5,
    ai_follow_up_notes = $6,
    ai_warranty_notes = $7,
    ai_job_category = $8,
    ai_client_sentiment = $9,
    ai_labor_hours = $10,
    ai_follow_up_required = $11,
    ai_safety_concerns = $12,
    ai_tags = $13,
    ai_raw_json = $14,
    ai_model_used = $15,
    ai_processed_at = $16,
    pdf_url = $17,
    email_sent_at = $18,
    completed_at = $19,
    updated_at = NOW()
WHERE id = $1
RETURNING id, company_id, technician_id, client_name, client_email, client_phone, job_address, job_lat, job_lng, job_type, technician_notes, submitted_at, completed_at, pipeline_status, audio_url, photo_urls, pdf_url, email_sent_at, created_at, updated_at, transcript, ai_summary, ai_work_performed, ai_follow_up_notes, ai_warranty_notes, ai_job_category, ai_client_sentiment, ai_labor_hours, ai_follow_up_required, ai_safety_concerns, ai_tags, ai_raw_json, ai_model_used, ai_processed_at, detected_language, report_language
`

type UpdateJobPipelineParams struct {
	ID                 pgtype.UUID        `json:"id"`
	PipelineStatus     string             `json:"pipeline_status"`
	Transcript         pgtype.Text        `json:"transcript"`
	AiSummary          pgtype.Text        `json:"ai_summary"`
	AiWorkPerformed    pgtype.Text        `json:"ai_work_performed"`
	AiFollowUpNotes    pgtype.Text        `json:"ai_follow_up_notes"`
	AiWarrantyNotes    pgtype.Text        `json:"ai_warranty_notes"`
	AiJobCategory      pgtype.Text        `json:"ai_job_category"`
	AiClientSentiment  pgtype.Text        `json:"ai_client_sentiment"`
	AiLaborHours       pgtype.Numeric     `json:"ai_labor_hours"`
	AiFollowUpRequired bool               `json:"ai_follow_up_required"`
	AiSafetyConcerns   []string           `json:"ai_safety_concerns"`
	AiTags             []string           `json:"ai_tags"`
	AiRawJson          []byte             `json:"ai_raw_json"`
	AiModelUsed        pgtype.Text        `json:"ai_model_used"`
	AiProcessedAt      pgtype.Timestamptz `json:"ai_processed_at"`
	PdfUrl             pgtype.Text        `json:"pdf_url"`
	EmailSentAt        pgtype.Timestamptz `json:"email_sent_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateJobPipeline(ctx context.Context, arg UpdateJobPipelineParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobPipeline,
		arg.ID,
		arg.PipelineStatus,
		arg.Transcript,
		arg.AiSummary,
		arg.AiWorkPerformed,
		arg.AiFollowUpNotes,
		arg.AiWarrantyNotes,
		arg.AiJobCategory,
		arg.AiClientSentiment,
		arg.AiLaborHours,
		arg.AiFollowUpRequired,
		arg.AiSafetyConcerns,
		arg.AiTags,
		arg.AiRawJson,
		arg.AiModelUsed,
		arg.AiProcessedAt,
		arg.PdfUrl,
		arg.EmailSentAt,
		arg.CompletedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TechnicianID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.JobAddress,
		&i.JobLat,
		&i.JobLng,
		&i.JobType,
		&i.TechnicianNotes,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.PipelineStatus,
		&i.AudioUrl,
		&i.PhotoUrls,
		&i.PdfUrl,
		&i.EmailSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transcript,
		&i.AiSummary,
		&i.AiWorkPerformed,
		&i.AiFollowUpNotes,
		&i.AiWarrantyNotes,
		&i.AiJobCategory,
		&i.AiClientSentiment,
		&i.AiLaborHours,
		&i.AiFollowUpRequired,
		&i.AiSafetyConcerns,
		&i.AiTags,
		&i.AiRawJson,
		&i.AiModelUsed,
		&i.AiProcessedAt,
		&i.DetectedLanguage,
		&i.ReportLanguage,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET pipeline_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, company_id, technician_id, client_name, client_email, client_phone, job_address, job_lat, job_lng, job_type, technician_notes, submitted_at, completed_at, pipeline_status, audio_url, photo_urls, pdf_url, email_sent_at, created_at, updated_at, transcript, ai_summary, ai_work_performed, ai_follow_up_notes, ai_warranty_notes, ai_job_category, ai_client_sentiment, ai_labor_hours, ai_follow_up_required, ai_safety_concerns, ai_tags, ai_raw_json, ai_model_used, ai_processed_at, detected_language, report_language
`

type UpdateJobStatusParams struct {
	ID             pgtype.UUID `json:"id"`
	PipelineStatus string      `json:"pipeline_status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.PipelineStatus)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TechnicianID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.JobAddress,
		&i.JobLat,
		&i.JobLng,
		&i.JobType,
		&i.TechnicianNotes,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.PipelineStatus,
		&i.AudioUrl,
		&i.PhotoUrls,
		&i.PdfUrl,
		&i.EmailSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transcript,
		&i.AiSummary,
		&i.AiWorkPerformed,
		&i.AiFollowUpNotes,
		&i.AiWarrantyNotes,
		&i.AiJobCategory,
		&i.AiClientSentiment,
		&i.AiLaborHours,
		&i.AiFollowUpRequired,
		&i.AiSafetyConcerns,
		&i.AiTags,
		&i.AiRawJson,
		&i.AiModelUsed,
		&i.AiProcessedAt,
		&i.DetectedLanguage,
		&i.ReportLanguage,
	)
	return i, err
}
