// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	DefaultLanguage      string             `json:"default_language"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	SubscriptionStatus   string             `json:"subscription_status"`
	TrialEndsAt          pgtype.Timestamptz `json:"trial_ends_at"`
	BillingEmail         pgtype.Text        `json:"billing_email"`
}

type Invitation struct {
	ID         pgtype.UUID        `json:"id"`
	CompanyID  pgtype.UUID        `json:"company_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	Token      string             `json:"token"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID                 pgtype.UUID        `json:"id"`
	CompanyID          pgtype.UUID        `json:"company_id"`
	TechnicianID       pgtype.UUID        `json:"technician_id"`
	ClientName         string             `json:"client_name"`
	ClientEmail        pgtype.Text        `json:"client_email"`
	ClientPhone        pgtype.Text        `json:"client_phone"`
	JobAddress         pgtype.Text        `json:"job_address"`
	JobLat             pgtype.Numeric     `json:"job_lat"`
	JobLng             pgtype.Numeric     `json:"job_lng"`
	JobType            pgtype.Text        `json:"job_type"`
	TechnicianNotes    pgtype.Text        `json:"technician_notes"`
	SubmittedAt        pgtype.Timestamptz `json:"submitted_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	PipelineStatus     string             `json:"pipeline_status"`
	AudioUrl           pgtype.Text        `json:"audio_url"`
	PhotoUrls          []string           `json:"photo_urls"`
	PdfUrl             pgtype.Text        `json:"pdf_url"`
	EmailSentAt        pgtype.Timestamptz `json:"email_sent_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Transcript         pgtype.Text        `json:"transcript"`
	AiSummary          pgtype.Text        `json:"ai_summary"`
	AiWorkPerformed    pgtype.Text        `json:"ai_work_performed"`
	AiFollowUpNotes    pgtype.Text        `json:"ai_follow_up_notes"`
	AiWarrantyNotes    pgtype.Text        `json:"ai_warranty_notes"`
	AiJobCategory      pgtype.Text        `json:"ai_job_category"`
	AiClientSentiment  pgtype.Text        `json:"ai_client_sentiment"`
	AiLaborHours       pgtype.Numeric     `json:"ai_labor_hours"`
	AiFollowUpRequired bool               `json:"ai_follow_up_required"`
	AiSafetyConcerns   []string           `json:"ai_safety_concerns"`
	AiTags             []string           `json:"ai_tags"`
	AiRawJson          []byte             `json:"ai_raw_json"`
	AiModelUsed        pgtype.Text        `json:"ai_model_used"`
	AiProcessedAt      pgtype.Timestamptz `json:"ai_processed_at"`
	DetectedLanguage   pgtype.Text        `json:"detected_language"`
	ReportLanguage     pgtype.Text        `json:"report_language"`
}

type JobMaterial struct {
	ID       pgtype.UUID `json:"id"`
	JobID    pgtype.UUID `json:"job_id"`
	Name     string      `json:"name"`
	Quantity pgtype.Text `json:"quantity"`
	Unit     pgtype.Text `json:"unit"`
}

type JobRecommendation struct {
	ID                 pgtype.UUID `json:"id"`
	JobID              pgtype.UUID `json:"job_id"`
	Description        string      `json:"description"`
	Urgency            string      `json:"urgency"`
	EstimatedCostRange pgtype.Text `json:"estimated_cost_range"`
	Resolved           bool        `json:"resolved"`
	ResolvedJobID      pgtype.UUID `json:"resolved_job_id"`
}

type JobTag struct {
	ID    pgtype.UUID `json:"id"`
	JobID pgtype.UUID `json:"job_id"`
	Tag   string      `json:"tag"`
}

type PipelineEvent struct {
	ID         pgtype.UUID        `json:"id"`
	JobID      pgtype.UUID        `json:"job_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Note       pgtype.Text        `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID pgtype.UUID        `json:"company_id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
