// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPipelineEvent = `-- name: CreatePipelineEvent :one
INSERT INTO pipeline_events (job_id, actor_id, from_status, to_status, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, actor_id, from_status, to_status, note, created_at
`

type CreatePipelineEventParams struct {
	JobID      pgtype.UUID `json:"job_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	Note       pgtype.Text `json:"note"`
}

func (q *Queries) CreatePipelineEvent(ctx context.Context, arg CreatePipelineEventParams) (PipelineEvent, error) {
	row := q.db.QueryRow(ctx, createPipelineEvent,
		arg.JobID,
		arg.ActorID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Note,
	)
	var i PipelineEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ActorID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listPipelineEventsByJob = `-- name: ListPipelineEventsByJob :many
SELECT id, job_id, actor_id, from_status, to_status, note, created_at FROM pipeline_events WHERE job_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListPipelineEventsByJob(ctx context.Context, jobID pgtype.UUID) ([]PipelineEvent, error) {
	rows, err := q.db.Query(ctx, listPipelineEventsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineEvent{}
	for rows.Next() {
		var i PipelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ActorID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
