// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, token string) (Invitation, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error)
	GetInvitationByToken(ctx context.Context, token string) (Invitation, error)
	GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetValidInvitationByToken(ctx context.Context, token string) (Invitation, error)
	ListJobsByCompany(ctx context.Context, companyID pgtype.UUID) ([]Job, error)
	ListJobsByTechnician(ctx context.Context, technicianID pgtype.UUID) ([]Job, error)
	ListUsersByCompany(ctx context.Context, companyID pgtype.UUID) ([]User, error)
	UpdateCompanySubscriptionStatus(ctx context.Context, arg UpdateCompanySubscriptionStatusParams) (Company, error)
	UpdateJobPipeline(ctx context.Context, arg UpdateJobPipelineParams) (Job, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
