// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, token string) (Invitation, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateJobMaterial(ctx context.Context, arg CreateJobMaterialParams) (JobMaterial, error)
	CreateJobRecommendation(ctx context.Context, arg CreateJobRecommendationParams) (JobRecommendation, error)
	CreateJobTag(ctx context.Context, arg CreateJobTagParams) (JobTag, error)
	CreatePipelineEvent(ctx context.Context, arg CreatePipelineEventParams) (PipelineEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteJobMaterial(ctx context.Context, id pgtype.UUID) error
	DeleteJobTag(ctx context.Context, arg DeleteJobTagParams) error
	GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error)
	GetInvitationByToken(ctx context.Context, token string) (Invitation, error)
	GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetValidInvitationByToken(ctx context.Context, token string) (Invitation, error)
	ListJobMaterialsByJob(ctx context.Context, jobID pgtype.UUID) ([]JobMaterial, error)
	ListJobRecommendationsByJob(ctx context.Context, jobID pgtype.UUID) ([]JobRecommendation, error)
	ListJobTagsByJob(ctx context.Context, jobID pgtype.UUID) ([]JobTag, error)
	ListJobsByCompany(ctx context.Context, companyID pgtype.UUID) ([]Job, error)
	ListJobsByTechnician(ctx context.Context, technicianID pgtype.UUID) ([]Job, error)
	ListPipelineEventsByJob(ctx context.Context, jobID pgtype.UUID) ([]PipelineEvent, error)
	ListUsersByCompany(ctx context.Context, companyID pgtype.UUID) ([]User, error)
	ResolveJobRecommendation(ctx context.Context, arg ResolveJobRecommendationParams) (JobRecommendation, error)
	UpdateCompanySubscriptionStatus(ctx context.Context, arg UpdateCompanySubscriptionStatusParams) (Company, error)
	UpdateJobPipeline(ctx context.Context, arg UpdateJobPipelineParams) (Job, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
